pipeline {
    agent any 
    triggers {
        // Polling the SCM to detect changes
        pollSCM('* * * * *') // This configuration polls the SCM every minute (adjust as needed)
        // GitHub webhook trigger
        githubPush()
    }
    environment {
        GIT_REPO = 'https://github.com/RamaRaju-personal-org/ami-jenkins.git'
        GIT_BRANCH = 'main'
        GIT_CREDENTIALS_ID = 'git-personal-access-token'
        DOCKER_HUB_CREDENTIALS = credentials('docker-hub-credentials-id')
    }
    stages {
        stage("Clean Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Clone static-site repo") {
            steps {
                echo "Cloning the repo"
                withCredentials([usernamePassword(credentialsId: "${GIT_CREDENTIALS_ID}", passwordVariable: 'GIT_TOKEN', usernameVariable: 'GIT_USERNAME')]) {
                    sh '''
                        git clone --branch ${GIT_BRANCH} https://${GIT_TOKEN}@github.com/RamaRaju-personal-org/ami-jenkins.git
                    '''
                }
            }
        }
        
        stage("Build the caddy image and push") {
            steps {
                echo "Building the image"
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials-id', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    sh '''
                        docker build -t ram2305/caddy:${BUILD_NUMBER} -f ami-jenkins/static-site/Dockerfile ami-jenkins/static-site
                        echo $PASS | docker login -u $USER --password-stdin
                        docker push ram2305/caddy:${BUILD_NUMBER}
                    '''
                }
            }
        }
    }
}
