name: Enforce Conventional Commits

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Commitlint
        run: npm install @commitlint/config-conventional @commitlint/cli

      - name: Create Commitlint configuration
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js

      - name: Run Commitlint on the latest commit
        run: |
          latest_commit=$(git rev-parse HEAD)
          git log -1 $latest_commit --pretty=%B | npx commitlint
