name: Enforce Conventional Commits

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1  # Fetch only the last one commits

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Commitlint
        run: npm install @commitlint/config-conventional @commitlint/cli

      - name: Create Commitlint configuration
        run: |
            echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js

      # %B outputs the raw commit message of the most recent commit message
      - name: Run Commitlint on the latest commit message
        run: |
          set -e
          git log -1 --pretty=%B | npx commitlint
