name: Conventional Commits

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get recent commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MSG" =~ ^Merge ]]; then
            COMMIT_MSG=$(git log -2 --pretty=%B | tail -1)
          fi
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV

      - name: Check commit message format
        run: |
          if ! [[ "${{ env.COMMIT_MSG }}" =~ ^(feat|fix|chore|docs|style|refactor)\(\S+\):\s.{1,} ]]; then
            echo "Commit message '${{ env.COMMIT_MSG }}' does not follow Conventional Commits format."
            exit 1
          else
            echo "Commit message follows Conventional Commits format."
          fi
