name: Build Jenkins AMI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Packer format
        id: fmt
        run: "packer fmt ."

      - name: Packer init
        id: init
        run: "packer init ."

      - name: Validate Packer template
        run: packer validate .
      
      - name: Prepare JCasC file to change user credientials
        run: |
          sed -i 's/ADMIN_USER/'"${{ secrets.JENKINS_ADMIN_USER }}"'/g' jenkins/jenkins.yaml
          sed -i 's/ADMIN_PASSWORD/'"${{ secrets.JENKINS_ADMIN_PASSWORD }}"'/g' jenkins/jenkins.yaml
          sed -i 's/docker_hub_username/'"${{ secrets.docker_hub_username }}"'/g' jenkins/jenkins.yaml
          sed -i 's/docker_hub_password/'"${{ secrets.docker_hub_password }}"'/g' jenkins/jenkins.yaml
          sed -i 's,git_repo_url,'"${{ secrets.GIT_REPO_URL }}"',g' jenkins/jenkins.yaml
          sed -i 's,git_repo_url,'"${{ secrets.GIT_REPO_URL }}"',g' jenkins/build-docker-image.groovy
          sed -i 's/git_token/'"${{ secrets.GIT_TOKEN }}"'/g' jenkins/jenkins.yaml
        shell: bash

      - name: Build AMI
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: packer build .
